import random
from locust import HttpUser, task, between

TOKENS = [
    {
    "email": "tiago+pol@acertolegal.com",
    "id": 425,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbytwb2xAYWNlcnRvbGVnYWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI3NTUwZGM0Yi1kMGI0LTRlYTMtYTVjYy00NDQ4ZjRlNDA4ZTEiLCJpZCI6NDI1LCJuYW1lIjoiUGxcdTAwZWRuaW8gT2xpdmVpcmEgTHV6IiwiZG9jIjoiMzE0MzI4NjY0NDMiLCJ0ZWwiOiIxMTk5OTk5OTk5OSIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.u7U2Hlhg-BewrruFHb7jJHKi9MiPipUA7sy-5b6rgpM",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbytwb2xAYWNlcnRvbGVnYWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiYjYzMzU3MTEtMjhkOS00YjVmLTlmMDAtM2VjMzc3MWMwYzg4IiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.wwZhAXHiN8nHP2Ic6VKej2m4K04nNoH_M8XdwI4x1Ag"
  },
  {
    "email": "viviane.boscaro@gmail.com",
    "id": 417,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW5lLmJvc2Nhcm9AZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiJiY2Y3M2Q4Ny04YzliLTRkNDEtYWY0ZC05ZDkxMWY0OTYxNDAiLCJpZCI6NDE3LCJuYW1lIjoiVml2aWFuZSBCb3NjYXJvIGRhIFNpbHZhIiwiZG9jIjoiMzI0MzI5MDY4NjEiLCJ0ZWwiOiIxMTk1NDkwMjY1NiIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.J-f_hqw1oHH9mbM-4n7a1pA5dR_akyaFIbmkLe_YXfw",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aXZpYW5lLmJvc2Nhcm9AZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiNmQ3ZDRhNGQtNGZiMi00ZWJiLTk5MjAtZjUzMWZhOWJlZjJlIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.fURgR9lcNlbNZ10ljYYL4A1ywl28BYU_mfZrooUaTzk"
  },
  {
    "email": "guilherme.andrade@paneaas.com",
    "id": 432,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJndWlsaGVybWUuYW5kcmFkZUBwYW5lYWFzLmNvbSIsImV4cCI6MTc2NDE3NDE0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoiYWNjZXNzIiwianRpIjoiYjgxNzhkODItZDI4Zi00YTQ2LWE5ZTYtMDhiODEzYzFhOGE2IiwiaWQiOjQzMiwibmFtZSI6Ikd1aWxoZXJtZSBTYWxlcyIsImRvYyI6IjE4MzU1NTczMDk5IiwidGVsIjoiMTQxMjQxMjQxMjQiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIn0.ZFgRKaDv6fdudluiIawpOEwDR0WsK-mbxnAf9QgNJZ8",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJndWlsaGVybWUuYW5kcmFkZUBwYW5lYWFzLmNvbSIsImV4cCI6MTc2NDc3NTM0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6IjA2ZTA2ODNkLTY5YjMtNDU3My04MzUxLWE3ZDUyMDA1MjA3OSIsInVzZXJfdHlwZSI6ImNsaWVudGUiLCJyb2xlIjpudWxsfQ.c5qvUuGbFh_AUlQsf1Kdqb2Q74FpzBCM7hiidO2U-Ug"
  },
  {
    "email": "giraldi+cpf@paneas.com",
    "id": 419,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpK2NwZkBwYW5lYXMuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI1NzUxNWYxMi01OTRjLTQ1NTUtODQxNi0xN2ZhMjY5ZThhZGMiLCJpZCI6NDE5LCJuYW1lIjoiQ2FybG9zIFBlZHJvc28gZGUgRmVycmF6IiwiZG9jIjoiMTkwNjA1ODQ1ODkiLCJ0ZWwiOiIxMTk1NzAwMTk1NCIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.od2yj7IertUv1oVkDSAxrog4hyHIhO0YJ30btffSEpQ",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpK2NwZkBwYW5lYXMuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiM2ZmMTQzN2YtMWEwNy00ODMyLTlkMjUtZTcyNDNhMzM5Y2VkIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.YOKye8k-nm0k-1wljKxjsVjezPAkEVRYsD5dXyCS7GQ"
  },
  {
    "email": "giraldi@paneas.com",
    "id": 420,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpQHBhbmVhcy5jb20iLCJleHAiOjE3NjQxNzQxNDEsImlhdCI6MTc2NDE3MDU0MSwidHlwZSI6ImFjY2VzcyIsImp0aSI6ImZmYzUwYjZkLTBkYjAtNDg5MC05NGQyLWUxOWMxODQxMjlmZiIsImlkIjo0MjAsIm5hbWUiOiJSb2RyaWdvIEZpb3JhbnRlIEdpcmFsZGkiLCJkb2MiOiIyOTU5NzA2NTg3OCIsInRlbCI6IjExOTczOTMxMzI0IiwidXNlcl90eXBlIjoiY2xpZW50ZSJ9.Ro-sIZWRlaVfcKTMNI_INHtX5W2odTEVmxFLiIBbGbo",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpQHBhbmVhcy5jb20iLCJleHAiOjE3NjQ3NzUzNDEsImlhdCI6MTc2NDE3MDU0MSwidHlwZSI6InJlZnJlc2giLCJqdGkiOiJiYjBlNGY3OC0zZGVjLTQ2NzMtODk2NS1jOWRkZTBiNjI1NmYiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIiwicm9sZSI6bnVsbH0.Kkmu1JYzDqAb4rRViSRj2VCThU5v1RF5I1KHS6dTVBA"
  },
  {
    "email": "tiago+sergio@acertolegal.com.br",
    "id": 430,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbytzZXJnaW9AYWNlcnRvbGVnYWwuY29tLmJyIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI3OGY0Y2Y5ZC0yMzkwLTRhYzQtOWY2OS1iZmI4ZjJiZjliZDYiLCJpZCI6NDMwLCJuYW1lIjoiU0VSR0lPIFJJQ0FSRE8gSVVTSU0gIiwiZG9jIjoiOTE5Nzc0MDE3OTEiLCJ0ZWwiOiIxMTk5OTk5OTk5OSIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.jTezMLxaiNhRmXlV0zHc9Vjyje5G2iefk5o88zYr6-U",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbytzZXJnaW9AYWNlcnRvbGVnYWwuY29tLmJyIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiZDE1ZjAzNzAtMmJjZS00YTU2LThmMjctYTVkNzZlZDMzNWM0IiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.eMfrP9eAV79c1qseI5LxKv9BVtge-sXgtuMpM0_xOOY"
  },
  {
    "email": "giraldi+jsmc@email.com",
    "id": 428,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpK2pzbWNAZW1haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiJjMDZmN2NjNC0wNmUxLTQ2MGUtOWFjOC00MmQ0MDk2YjYzYmUiLCJpZCI6NDI4LCJuYW1lIjoiSm9cdTAwZTNvIGRhIFNpbHZhIE1lbmRlcyBDYW1wb3MiLCJkb2MiOiI0MjEwMDUxNjQwMCIsInRlbCI6IjExOTU3MDAxOTU0IiwidXNlcl90eXBlIjoiY2xpZW50ZSJ9.z24RtnQbDDNqKXbOcPY4SY3PrqcQRZLNMNuvBHqjbow",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaXJhbGRpK2pzbWNAZW1haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiOWUyNmVkMzktYzM4MC00YTMyLTgyZWUtNjBiMGU5YzQ4ZTgzIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.g5JMwY1CdvmqU9xNfc98LS_YPr6mixns534cKIc9Vsg"
  },
  {
    "email": "guilherme.andrade@paneas.com",
    "id": 433,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJndWlsaGVybWUuYW5kcmFkZUBwYW5lYXMuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI5Njg5ZDEzNi0zNDFhLTRjZDgtYjE3YS01ODEzOWUzNjBiN2QiLCJpZCI6NDMzLCJuYW1lIjoiR3VpbGhlcm1lIFNhbGVzIiwiZG9jIjoiNzMwNDEyOTcwMDAiLCJ0ZWwiOiIxNTMyNTIzNTIzNSIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.xx6cUBendPKB6e-8ECMb3eVqfEZswzvhFCmyIDnrT04",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJndWlsaGVybWUuYW5kcmFkZUBwYW5lYXMuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiY2I1MzNjNjMtYjZkOC00OTk4LWJmYzMtNTI5MjZmYTA5ZDcwIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.vK6gPCc021mi__ClsV6ctA-f-r-XZU5lZYMglKGTvMw"
  },
  {
    "email": "henrique+erl@paneas.com",
    "id": 421,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJoZW5yaXF1ZStlcmxAcGFuZWFzLmNvbSIsImV4cCI6MTc2NDE3NDE0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoiYWNjZXNzIiwianRpIjoiNjAyOWRjYmMtZTk0Ni00YmM5LTk3NzEtYmIxZDhhY2M3NTY1IiwiaWQiOjQyMSwibmFtZSI6IkVkdWFyZG8gUm9kcmlndWVzIEx1eiIsImRvYyI6IjgxNDU4OTYyMDc1IiwidGVsIjoiNDc5OTEwNDM3ODMiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIn0.IPbzP8ERI9mRWRVDMKQ_9_7_RlkO6Xz3wd0wCySYOgg",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJoZW5yaXF1ZStlcmxAcGFuZWFzLmNvbSIsImV4cCI6MTc2NDc3NTM0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6Ijg5MWY3M2E2LTIwYTUtNDQ2NC1hMGM1LThjNDU1NGZkMzZlYSIsInVzZXJfdHlwZSI6ImNsaWVudGUiLCJyb2xlIjpudWxsfQ.Cr4cDFl7gw22Gds9x_7R1XGafyoBDw6RdRb5HGOrC84"
  },
  {
    "email": "tiagovalim3+szl@gmail.com",
    "id": 418,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytzemxAZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiIxYzZkZDhkZC03YTdiLTQ3ODYtOTcwNS1kMmRjMGEyYWI1Y2EiLCJpZCI6NDE4LCJuYW1lIjoiU29uaWEgWm9yb2FzdHJhIExpbVx1MDBlM28iLCJkb2MiOiI1NTE1MzI2MzUwOSIsInRlbCI6IjExOTk5OTk5OTk5IiwidXNlcl90eXBlIjoiY2xpZW50ZSJ9.6acwMOsPYSaStWbF0CztUraGFpp_-MSL7fWWcoFsELU",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytzemxAZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiYzdhYjhmYTItMTBhYy00N2NiLWIyODEtYjNjN2I4YmJiNWZlIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.FvIUOynAO5XOGfoQ7HD-AYw6IXkse8faJnnx_Wb94HU"
  },
  {
    "email": "tiagovalim3+ect@gmail.com",
    "id": 423,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytlY3RAZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiIxNWY4N2E2Yy1iYTdhLTQ4YjMtOGQzMC1lM2M2NDZhOTQzMzIiLCJpZCI6NDIzLCJuYW1lIjoiRWxhaW5lIENhcmRvc28gVGVzdGEiLCJkb2MiOiIxMzAzNTU2NTM3NiIsInRlbCI6IjExOTgzNDg5MjM0IiwidXNlcl90eXBlIjoiY2xpZW50ZSJ9.shcHbfN_E0fFexcQJXyonlV6mo65idEhnCUaedUWh_o",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytlY3RAZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiZTYxYjk2Y2MtNTUwNi00ZDA0LTg5ZGItYWI4ZDUyMmJjMzBjIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.YN050QgSwY67Y1TeYPDY7lVqkz3JDmU1e2KoWjmA3S8"
  },
  {
    "email": "tiago+mds@acertolegal.com.br",
    "id": 429,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbyttZHNAYWNlcnRvbGVnYWwuY29tLmJyIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiJjNDlmZTViNC1kNWUyLTRmNWQtOGQzMC0zZTA5ZTdjYTYwNmYiLCJpZCI6NDI5LCJuYW1lIjoiTWFyZHNvdSBTb3V6YSIsImRvYyI6IjA1MDkzMzg1NTA2IiwidGVsIjoiMTE5OTk5OTk5OTkiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIn0.5GbVVtNEhp4wpHtaJ775WupVTAKhJpC_nqOlCLy5tjw",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnbyttZHNAYWNlcnRvbGVnYWwuY29tLmJyIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiYjExZmMxMTYtYzhlZS00ZmNjLTlkMDYtNTE1YjQ1ZmNiZTE5IiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.-i4AZpO5HtorX9i_714ggitQefR67a9XccFCU_pJlIc"
  },
  {
    "email": "tiagovalim3+hpc@gmail.com",
    "id": 431,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytocGNAZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiIwOGU0ZGM0Yy00YmM3LTQ5MDUtYTdiZC01ZTk4YzRhMDI2ZTgiLCJpZCI6NDMxLCJuYW1lIjoiSGVsZW5hIFBlZHJvc28gQ29lbGhvIiwiZG9jIjoiMDE5NTI4MzkwMjUiLCJ0ZWwiOiIxMTk5OTk5OTk5OSIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.ic5US3GoBnSqFSugUQWatLLoprZYUaA-r3FPZ_oQMzU",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytocGNAZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiNWExZjQxNDktMTEwZS00MGFjLWE3NjEtNGVmZDkxMmFlODJjIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.QRxWV-9tfkDIYCxU8tgIvMqFvyuXwxw8mDRBDS-DRNM"
  },
  {
    "email": "tiagovalim3+fqc@gmail.com",
    "id": 424,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytmcWNAZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI4NjgxZjgzZC02MzNmLTQ2ZjYtODUxOC1hMTNmM2M0MTcyOTMiLCJpZCI6NDI0LCJuYW1lIjoiRmFiaWFuYSBRdWVpcm96IGRhcyBDb2xpbmFzIiwiZG9jIjoiNjQ5NjQxMTg5MTYiLCJ0ZWwiOiIxMTAwMDAwMDAwMCIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.wj3Iw1y8Q2l0mo_kUrdhxsT1hO6swXFjqNUTp3uu-IM",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytmcWNAZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiMzAxZjc2NDItNWNjYi00MTUwLTg3YmUtOTFmZTZjYzNkNThlIiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.n9nbjpUeS8QKDBwc4CVSgvTtpi4ZumFn1wtiBZ1w8RQ"
  },
  {
    "email": "tiagovalim3+rmdc@gmail.com",
    "id": 422,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytybWRjQGdtYWlsLmNvbSIsImV4cCI6MTc2NDE3NDE0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoiYWNjZXNzIiwianRpIjoiNzc3MDIyMjAtMWQwNS00MDZhLTk4N2UtM2IxNGQzODNlNjgwIiwiaWQiOjQyMiwibmFtZSI6IlJhZmFlbGEgTXVyb2xvIERhIFZpbmNpIiwiZG9jIjoiOTQ4MzAyNjY1MjAiLCJ0ZWwiOiIxMTk5OTk5OTk5OSIsInVzZXJfdHlwZSI6ImNsaWVudGUifQ.5uYEndXcuCu4ZkzQAEo0vwwlSqgt2Zr2-H9Y2D9RhMg",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytybWRjQGdtYWlsLmNvbSIsImV4cCI6MTc2NDc3NTM0MSwiaWF0IjoxNzY0MTcwNTQxLCJ0eXBlIjoicmVmcmVzaCIsImp0aSI6ImFiZGQ2MDQzLWExZmYtNGEwNy1iZWI3LTAyYjRkNTgzODBlYiIsInVzZXJfdHlwZSI6ImNsaWVudGUiLCJyb2xlIjpudWxsfQ.gBIZAg2GTtu-quv68HzXTv-U88S46gv1AhYvbWGixoQ"
  },
  {
    "email": "tiagovalim3+pmp@gmail.com",
    "id": 427,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytwbXBAZ21haWwuY29tIiwiZXhwIjoxNzY0MTc0MTQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJhY2Nlc3MiLCJqdGkiOiI2ZWUxOWJlYy0zNDUzLTRjY2MtODcwNi1kYTlmNzc2YTJkOWEiLCJpZCI6NDI3LCJuYW1lIjoiUEFVTE8gTUVORE9OXHUwMGM3QSBQSU5UTyIsImRvYyI6IjIxMzgyNjAyODM5IiwidGVsIjoiMTE5OTk5OTk5OTkiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIn0.OnI1q_Gw5F3EteVLzpqW3Ubiz5O9HZSozSeUFyNI1tA",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGltMytwbXBAZ21haWwuY29tIiwiZXhwIjoxNzY0Nzc1MzQxLCJpYXQiOjE3NjQxNzA1NDEsInR5cGUiOiJyZWZyZXNoIiwianRpIjoiMTYyMmYwNzctYmJhMS00OWRlLTgwMjYtMWE2Mzg5M2Q0ZGE0IiwidXNlcl90eXBlIjoiY2xpZW50ZSIsInJvbGUiOm51bGx9.K-_FuWppYIPO5nnL_EKhOoGiPGhFwTunx_EKEX5nhio"
  },
  {
    "email": "tiagovali3+apd@gmail.com",
    "id": 426,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGkzK2FwZEBnbWFpbC5jb20iLCJleHAiOjE3NjQxNzQxNDEsImlhdCI6MTc2NDE3MDU0MSwidHlwZSI6ImFjY2VzcyIsImp0aSI6IjI1ZDBiNTIyLTY0ZmQtNDNhYS1iNTgzLTU3OTRkZDAxMWU2OSIsImlkIjo0MjYsIm5hbWUiOiJBbmEgUGF1bGEgRGVudGVsbG8gTHVpeiIsImRvYyI6IjE5MjIyNDEwODMxIiwidGVsIjoiMTE5OTk5OTk5OTkiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIn0.f4pOU0fUC-yfgyZw4gf6n0G_QPrlHqW3lpfrVQNODSo",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0aWFnb3ZhbGkzK2FwZEBnbWFpbC5jb20iLCJleHAiOjE3NjQ3NzUzNDEsImlhdCI6MTc2NDE3MDU0MSwidHlwZSI6InJlZnJlc2giLCJqdGkiOiJiNmNmOTlhNi0xYzliLTQ4YmUtYjYzZC03MmY0MjBmMmFiNWMiLCJ1c2VyX3R5cGUiOiJjbGllbnRlIiwicm9sZSI6bnVsbH0.ku_Vz9wtndQg9F59RzrVQBlRxQH-i5xfKAOlG213xdw"
  }
]

class ChatApiUser(HttpUser):
    wait_time = between(1, 3)  # intervalo entre requisições

    def on_start(self):
        # Cada usuário pega um token aleatório da lista
        user = random.choice(TOKENS)
        self.token = user["accessToken"]
        self.client.headers.update({"Authorization": f"Bearer {self.token}"})

    @task
    def criar_thread(self):
        self.client.post("/rag-chat/create-thread-v2")

    # def consultar_historico(self):
    #     self.client.get("/rag-chat/historico/v2", params={"thread_id": "thread_25f587fbd0a1_1764077429"})

    # @task
    # def estatisticas_sessao(self):
    #     self.client.get("/rag-chat/session/stats")
